# DON'T TOUCH Config-Version OR THINGS WILL BREAK
Config-Version: 1.2.0
# Name of Spec
shiny:
  # Set whether the message is sent to all players, or just on the player it spawned on. (true/false)
  Global-Alert: true
  # Message that gets sent to all players when the Pokemon with the spec spawns in.
  SpawnMessage: "<yellow>A shiny <gold>{pokemon} <yellow>spawned on <gold>{player} at x = {x}!"
  # Message that gets sent to all players when the Pokemon with the spec spawns in from a PokeSnack
  SpawnMessage-Snack: "<yellow>A shiny <gold>{pokemon} <yellow>was lured in by a PokeSnack at {x}, {y}, {z}!"
  # Message that gets sent to all players when the Pokemon with the spec faints.
  FaintMessage: "<red>A shiny <dark_red>{pokemon}<red> has fainted."
  # Message that gets sent to all players when the Pokemon with the spec is captured.
  CaptureMessage: "<yellow>A shiny <gold>{pokemon} <yellow>has been captured by <gold>{player}!"
  # Message that gets sent to all players when the Pokemon with the spec is revived from a fossil.
  ReviveMessage: "<yellow>A shiny <gold>{pokemon} <yellow>has been revived by <gold>{player}!"
legendary:
  Global-Alert: true
  SpawnMessage: "<green>A Legendary <dark_green>{pokemon} <green>has spawned near <dark_green>{player}!"
  FaintMessage: "<red>A Legendary <dark_red>{pokemon}<red> has fainted."
  CaptureMessage: "<green>A Legendary <dark_green>{pokemon} <green>has been captured by <dark_green>{player}!"
  ReviveMessage: "<green>A Legendary <dark_green>{pokemon} <green>has been revived by <dark_green>{player}!"
mythical:
  Global-Alert: true
  SpawnMessage: "<light_purple>A Mythical <dark_purple>{pokemon} <light_purple>has spawned near <dark_purple>{player}!"
  FaintMessage: "<red>A Mythical <dark_red>{pokemon}<red> has fainted."
  CaptureMessage: "<light_purple>A Mythical <dark_purple>{pokemon} <light_purple>has been captured by <dark_purple>{player}!"
  ReviveMessage: "<light_purple>A Mythical <dark_purple>{pokemon} <light_purple>has been revived by <dark_purple>{player}!"
ultrabeast:
  Global-Alert: true
  SpawnMessage: "<aqua>An Ultra Beast <dark_aqua>{pokemon} <aqua>has spawned near <dark_aqua>{player}!"
  FaintMessage: "<red>A Ultra Beast <dark_red>{pokemon}<red> has fainted."
  CaptureMessage: "<aqua>A Ultra Beast <dark_aqua>{pokemon} <aqua>has been captured by <dark_aqua>{player}!"
  ReviveMessage: "<aqua>A Ultra Beast <dark_aqua>{pokemon} <aqua>has been revived by <dark_aqua>{player}!"